# config/prod.yaml
scene: 
  path: "resources/scenes/identity"  # 默认路径

embed:
  embed_model: "nomic-embed-text"
  embed_host: "http://localhost:11434"
  embed_dim: 768
  embed_max_token_size: 8192

llm:
  # model_name: "deepseek-r1:7b"
  model_name: "qwq"
  model_host: "http://localhost:11434"
  num_ctx: 8192
  llm_model_max_token_size: 8192
  llm_model_max_async: 4

tiktoken:
  cache_dir: "resources/tiktok"

rag_api:
  log_path: "logs/rag_api.log"
  log_level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_rotation: "10 MB"

server:
    host: "0.0.0.0"
    port: 50051
    log_path: "logs/server.log"
    log_level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL
    log_rotation: "10 MB"


version: "v0.2.1"